### ISSUE TITLE
HelloWorld.class not found

### ISSUE THREAD

**Issue by coder543** [maxmcc/rust-jvm#1]
Hey,

I'm trying to get this running on my machine, and I've run into some interesting issues when trying to run `cargo test`. The first is a file not found exception for HelloWorld.class, because the working directory for running tests is the root of the crate, and the file path isn't "data/HelloWorld.class". Once I copied those class files into the root of the crate, the test is able to move further, to the point that it is unable to load `java/lang/Object`. I copied my `rt.jar` file from `/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar` into the root of the crate, and then `unzip`ped it there.  This allows the test to get all the way through loading stuff. Unfortunately, it then gets a NullPointerException while running the `main` function of `HelloWorld.class`.

Given the disassembly of `HelloWorld.class`

`javap -c HelloWorld.class`

```
Compiled from "HelloWorld.java"
public class HelloWorld {
  public HelloWorld();
    Code:
       0: aload_0
       1: invokespecial #1                  // Method java/lang/Object."<init>":()V
       4: return

  public static void main(java.lang.String[]);
    Code:
       0: getstatic     #2                  // Field java/lang/System.out:Ljava/io/PrintStream;
       3: ldc           #3                  // String Hello, World
       5: invokevirtual #4                  // Method java/io/PrintStream.println:(Ljava/lang/String;)V
       8: return
}

```

The crash is occurring on `5: invokevirtual #4`, which is the `println` call. Looking at the `args` variable right before it emits the `NullPointerException`, the first value on the stack is indeed a `NullReference`.

That's as far as I got just winging it on someone else's code base. This project looks really interesting, but `README.md` _really_ needs to be updated to show the _current_ status of the project, not just the projected schedule, and a little documentation is needed for how to get up and running. I don't think extracting `rt.jar` into the root of the crate is the solution used by the team members of this project, but I have no idea what the right method is. Any help would be appreciated.

**Comment by maxmcc** [comment]
Hi coder543,

Thanks for your interest in the project. Since it was completed as a final project for a course, we don't plan to continue developing it or providing support.

I'm sorry we didn't make this more explicit in the project README. I'll update it soon to reflect the current status of the project.

**Comment by coder543** [comment]
If the code were given a license (say, MIT or GPL), and just a few key pointers in the README file, some community members might want to pick it up and play with it, myself included. I definitely understand the feeling of being done with a class project, though.

**Comment by coder543** [comment]
or if it were given the Apache 2 license mentioned in the README as the eventual, intended license, now that I see that line.

**Comment by maxmcc** [comment]
Thanks for the suggestion. I'm updating some parts of the project right now (including adding an actually useful README and a license). The updated code and instructions should solve the issues you were encountering.

**Comment by coder543** [comment]
that's awesome! thank you.
